# Generated by Django 5.0.2 on 2024-02-08 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=255)),
                ('qr_code', models.ImageField(upload_to='btc_qrcodes/')),
                ('wallet_address', models.CharField(max_length=255)),
                ('network', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'BTC',
                'verbose_name_plural': 'BTC',
            },
        ),
        migrations.CreateModel(
            name='USDT_ERC20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=255)),
                ('qr_code', models.ImageField(upload_to='usdt_erc20_qrcodes/')),
                ('wallet_address', models.CharField(max_length=255)),
                ('network', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'USDT ERC20',
                'verbose_name_plural': 'USDT ERC20',
            },
        ),
        migrations.CreateModel(
            name='USDT_TRC20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=255)),
                ('qr_code', models.ImageField(upload_to='usdt_trc20_qrcodes/')),
                ('wallet_address', models.CharField(max_length=255)),
                ('network', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'USDT TRC20',
                'verbose_name_plural': 'USDT TRC20',
            },
        ),
        migrations.CreateModel(
            name='AccountSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(blank=True, choices=[('USDT_TRC20', 'USDT TRC20'), ('USDT_ERC20', 'USDT ERC20'), ('BTC', 'BTC')], max_length=20, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Funds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('USDT_TRC20', 'USDT TRC20'), ('USDT_ERC20', 'USDT ERC20'), ('BTC', 'BTC')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confirmed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funds',
                'verbose_name_plural': 'Funds',
            },
        ),
    ]
