# Generated by Django 5.0.2 on 2024-02-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='about_you',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='job',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Include country code', max_length=20, null=True),
        ),
    ]
